/**
 * Localised field names.
 * Used in detail display.
 */
pz2_client.prototype.localisations['detail-label'] = {

	'de': {
		'title': 'Titel',
		'author': 'Autor',
		'author-plural': 'Autoren',
		'author-clean': 'Autor',
		'author-clean-plural': 'Autoren',
		'other-person': 'Person',
		'other-person-plural': 'Personen',
		'other-person-clean': 'Person',
		'other-person-clean-plural': 'Personen',
		'corporate': 'Körperschaft',
		'corporate-plural': 'Körperschaften',
		'corporate-clean': 'Körperschaft',
		'corporate-clean-plural': 'Körperschaften',
		'meeting': 'Kongress',
		'meeting-plural': 'Kongresse',
		'meeting-clean': 'Kongress',
		'meeting-clean-plural': 'Kongresse',
		'medium': 'Art',
		'description': 'Information',
		'description-plural': 'Informationen',
		'abstract': 'Abstract',
		'series-title': 'Reihe',
		'issn': 'ISSN',
		'acronym-issn': 'Internationale Standardseriennummer',
		'isbn-minimal': 'ISBN',
		'acronym-isbn-minimal': 'Internationale Standardbuchnummer',
		'doi': 'DOI',
		'acronym-doi': 'Document Object Identifier: Mit dem Link zu dieser Nummer kann das Dokument im Netz gefunden werden.',
		'doi-plural': 'DOIs',
		'keyword': 'Schlagwort',
		'keyword-plural': 'Schlagwörter',
		'classification-msc': 'MSC',
		'acronym-classification-msc': 'Mathematics Subject Classification',
		'map': 'Ort',
		'mapscale': 'Maßstab',
		'creator': 'erfasst von',
		'verfügbarkeit': 'Verfügbarkeit'
	},

	'en': {
		'title': 'Title',
		'author': 'Author',
		'author-plural': 'Authors',
		'author-clean': 'Author',
		'author-clean-plural': 'Authors',
		'other-person': 'Person',
		'other-person-plural': 'People',
		'other-person-clean': 'Person',
		'other-person-clean-plural': 'People',
		'corporate': 'Corporate Body',
		'corporate-plural': 'Corporate Bodies',
		'corporate-clean': 'Corporate Body',
		'corporate-clean-plural': 'Corporate Bodies',
		'meeting': 'Corporate Body',
		'meeting-plural': 'Meetings',
		'meeting-clean': 'Meeting',
		'meeting-clean-plural': 'Meetings',
		'medium': 'Type',
		'description': 'Information',
		'description-plural': 'Information',
		'abstract': 'Abstract',
		'series-title': 'Series',
		'issn': 'ISSN',
		'acronym-issn': 'International Standard Series Number',
		'isbn-minimal': 'ISBN',
		'acronym-isbn-minimal': 'International Standard Book Number',
		'doi': 'DOI',
		'acronym-doi': 'Document Object Identifier: Use the link to load the document.',
		'doi-plural': 'DOIs',
		'keyword': 'Keyword',
		'keyword-plural': 'Keywords',
		'classification-msc': 'MSC',
		'acronym-classification-msc': 'Mathematics Subject Classification',
		'map': 'Location',
		'mapscale': 'Scale',
		'creator': 'catalogued by',
		'verfügbarkeit': 'Availability'
	}

};
