/**
 * Localised country names for ISO 3166-1 alpha-2 country codes.
 */
pz2_client.prototype.localisations['facet-country'] = {

	'de': {
		'AD': 'Andorra',
		'AE': 'Vereinigte Arabische Emirate',
		'AF': 'Afghanistan',
		'AG': 'Antigua und Barbuda',
		'AI': 'Anguilla',
		'AL': 'Albanien',
		'AM': 'Armenien',
		'AO': 'Angola',
		'AQ': 'Antarktika',
		'AR': 'Argentinien',
		'AS': 'Amerikanisch-Samoa',
		'AT': 'Österreich',
		'AU': 'Australien',
		'AW': 'Aruba',
		'AX': 'Åland',
		'AZ': 'Aserbaidschan',
		'BA': 'Bosnien-Herzegowina',
		'BB': 'Barbados',
		'BD': 'Bangladesch',
		'BE': 'Belgien',
		'BF': 'Burkina Faso',
		'BG': 'Bulgarien',
		'BH': 'Bahrain',
		'BI': 'Burundi',
		'BJ': 'Benin',
		'BL': 'Saint Barthélemy',
		'BM': 'Bermudainseln',
		'BN': 'Brunei',
		'BO': 'Bolivien',
		'BQ': 'Britisches Antarktis-Territorium',
		'BR': 'Brasilien',
		'BS': 'Bahamas',
		'BT': 'Bhutan',
		'BV': 'Bouvetinsel',
		'BW': 'Botswana',
		'BY': 'Weißrussland',
		'BZ': 'Belize',
		'CA': 'Kanada',
		'CC': 'Kokosinseln',
		'CD': 'Kongo <Demokratische Republik>',
		'CF': 'Zentralafrikanische Republik',
		'CG': 'Kongo',
		'CH': 'Schweiz',
		'CI': 'Elfenbeinküste',
		'CK': 'Cookinseln',
		'CL': 'Chile',
		'CM': 'Kamerun',
		'CN': 'China',
		'CO': 'Kolumbien',
		'CR': 'Costa Rica',
		'CU': 'Kuba',
		'CV': 'Kapverdische Inseln',
		'CW': 'Curaçao',
		'CX': 'Christmas Island',
		'CY': 'Zypern',
		'CZ': 'Tschechische Republik',
		'DE': 'Deutschland',
		'DJ': 'Dschibuti',
		'DK': 'Dänemark',
		'DM': 'Dominica',
		'DO': 'Dominikanische Republik',
		'DZ': 'Algerien',
		'EC': 'Ecuador',
		'EE': 'Estland',
		'EG': 'Ägypten',
		'EH': 'Westsahara',
		'ER': 'Eritrea',
		'ES': 'Spanien',
		'ET': 'Äthiopien',
		'FI': 'Finnland',
		'FJ': 'Fidschi',
		'FK': 'Falklandinseln',
		'FM': 'Mikronesien',
		'FO': 'Färöer',
		'FR': 'Frankreich',
		'GA': 'Gabun',
		'GB': 'Großbritannien',
		'GD': 'Grenada',
		'GE': 'Georgien',
		'GF': 'Französisch-Guayana',
		'GG': 'Guernsey',
		'GH': 'Ghana',
		'GI': 'Gibraltar',
		'GL': 'Grönland',
		'GM': 'Gambia',
		'GN': 'Guinea',
		'GP': 'Guadeloupe',
		'GQ': 'Äquatorialguinea',
		'GR': 'Griechenland',
		'GS': 'Südgeorgien und Südliche Sandwichinseln',
		'GT': 'Guatemala',
		'GU': 'Guam',
		'GW': 'Guinea-Bissau',
		'GY': 'Guyana',
		'HK': 'Hongkong',
		'HM': 'Heard und McDonaldinseln',
		'HN': 'Honduras',
		'HR': 'Kroatien',
		'HT': 'Haiti',
		'HU': 'Ungarn',
		'ID': 'Indonesien',
		'IE': 'Irland',
		'IL': 'Israel',
		'IM': 'Insel Man',
		'IN': 'Indien',
		'IO': 'Britisches Territorium im Indischen Ozean',
		'IQ': 'Irak',
		'IR': 'Iran',
		'IS': 'Island',
		'IT': 'Italien',
		'JE': 'Jersey',
		'JM': 'Jamaika',
		'JO': 'Jordanien',
		'JP': 'Japan',
		'KE': 'Kenia',
		'KG': 'Kirgisien',
		'KH': 'Kambodscha',
		'KI': 'Kiribati',
		'KM': 'Komoren',
		'KN': 'Saint Kitts und Nevis',
		'KP': 'Nordkorea',
		'KR': 'Südkorea',
		'KW': 'Kuwait',
		'KY': 'Kaiman Inseln',
		'KZ': 'Kasachstan',
		'LA': 'Laos',
		'LB': 'Libanon',
		'LC': 'Saint Lucia',
		'LI': 'Liechtenstein',
		'LK': 'Sri Lanka',
		'LR': 'Liberia',
		'LS': 'Lesotho',
		'LT': 'Litauen',
		'LU': 'Luxemburg',
		'LV': 'Lettland',
		'LY': 'Libyen',
		'MA': 'Marokko',
		'MC': 'Monaco',
		'MD': 'Moldawien',
		'ME': 'Montenegro',
		'MF': 'St. Martin (Französicher Teil)',
		'MG': 'Madagaskar',
		'MH': 'Marshallinseln',
		'MK': 'Makedonien',
		'ML': 'Mali',
		'MM': 'Birma',
		'MN': 'Mongolei',
		'MO': 'Macao',
		'MP': 'Nördliche Marianen',
		'MQ': 'Martinique',
		'MR': 'Mauretanien',
		'MS': 'Montserrat',
		'MT': 'Malta',
		'MU': 'Mauritius',
		'MV': 'Malediven',
		'MW': 'Malawi',
		'MX': 'Mexiko',
		'MY': 'Malaysia',
		'MZ': 'Mozambique',
		'NA': 'Namibia',
		'NC': 'Neukaledonien',
		'NE': 'Niger',
		'NF': 'Norfolk-Insel',
		'NG': 'Nigeria',
		'NI': 'Nicaragua',
		'NL': 'Niederlande',
		'NO': 'Norwegen',
		'NP': 'Nepal',
		'NR': 'Nauru',
		'NU': 'Niue',
		'NZ': 'Neuseeland',
		'OM': 'Oman',
		'PA': 'Panama',
		'PE': 'Peru',
		'PF': 'Französisch-Polynesien',
		'PG': 'Papua-Neuguinea',
		'PH': 'Philippinen',
		'PK': 'Pakistan',
		'PL': 'Polen',
		'PM': 'Saint-Pierre-et-Miquelon',
		'PN': 'Pitcairn',
		'PR': 'Puerto Rico',
		'PS': 'Palästinensische Autonomiegebiete',
		'PT': 'Portugal',
		'PW': 'Palauinseln',
		'PY': 'Paraguay',
		'QA': 'Katar',
		'RE': 'Réunion',
		'RO': 'Rumänien',
		'RS': 'Serbien',
		'RU': 'Russland, Sowjetunion',
		'RW': 'Rwanda',
		'SA': 'Saudi-Arabien',
		'SB': 'Salomonen',
		'SC': 'Seychellen',
		'SD': 'Sudan',
		'SE': 'Schweden',
		'SG': 'Singapur',
		'SH': 'Sankt Helena',
		'SI': 'Slowenien',
		'SJ': 'Svalbard und Jan Mayen',
		'SK': 'Slowakei',
		'SL': 'Sierra Leone',
		'SM': 'San Marino',
		'SN': 'Senegal',
		'SO': 'Somalia',
		'SR': 'Surinam',
		'SS': 'Südsudan',
		'ST': 'São Tomé und Príncipe',
		'SV': 'El Salvador',
		'SX': 'St. Martin (Niederländischer Teil)',
		'SY': 'Syrien',
		'SZ': 'Swasiland',
		'TC': 'Turks- und Caicos-Inseln',
		'TD': 'Tschad',
		'TF': 'Französische Südgebiete',
		'TG': 'Togo',
		'TH': 'Thailand',
		'TJ': 'Tadschikistan',
		'TK': 'Tokelau',
		'TL': 'Osttimor',
		'TM': 'Turkmenistan',
		'TN': 'Tunesien',
		'TO': 'Tonga',
		'TR': 'Türkei',
		'TT': 'Trinidad und Tobago',
		'TV': 'Tuvalu',
		'TW': 'Taiwan',
		'TZ': 'Tansania',
		'UA': 'Ukraine',
		'UG': 'Uganda',
		'UM': 'Amerikanische Überseeinseln',
		'US': 'USA',
		'UY': 'Uruguay',
		'UZ': 'Usbekistan',
		'VA': 'Vatikanstadt',
		'VC': 'Saint Vincent and the Grenadines',
		'VE': 'Venezuela',
		'VG': 'Jungferninseln, Großbritannien',
		'VI': 'Jungferninseln, U.S.',
		'VN': 'Vietnam',
		'VU': 'Vanuatu',
		'WF': 'Wallis und Futuna',
		'WS': 'Westsamoa',
		'YE': 'Jemen',
		'YT': 'Mayotte',
		'ZA': 'Südafrika',
		'ZM': 'Sambia',
		'ZW': 'Simbabwe',
		// Non-Standard codes
		'EU': 'Europa',
		'II': 'International'
	},

	'en': {
		'AD': 'Andorra',
		'AE': 'United Arab Emirates',
		'AF': 'Afghanistan',
		'AG': 'Antigua and Barbuda',
		'AI': 'Anguilla',
		'AL': 'Albania',
		'AM': 'Armenia',
		'AO': 'Angola',
		'AQ': 'Antarctica',
		'AR': 'Argentina',
		'AS': 'American Samoa',
		'AT': 'Austria',
		'AU': 'Australia',
		'AW': 'Aruba',
		'AX': 'Åland Islands',
		'AZ': 'Azerbaijan',
		'BA': 'Bosnia and Herzegovina',
		'BB': 'Barbados',
		'BD': 'Bangladesh',
		'BE': 'Belgium',
		'BF': 'Burkina Faso',
		'BG': 'Bulgaria',
		'BH': 'Bahrain',
		'BI': 'Burundi',
		'BJ': 'Benin',
		'BL': 'Saint Barthélemy',
		'BM': 'Bermuda',
		'BN': 'Brunei Darussalam',
		'BO': 'Bolivia, Plurinational State of',
		'BQ': 'Bonaire, Sint Eustatius and Saba',
		'BR': 'Brazil',
		'BS': 'Bahamas',
		'BT': 'Bhutan',
		'BV': 'Bouvet Island',
		'BW': 'Botswana',
		'BY': 'Belarus',
		'BZ': 'Belize',
		'CA': 'Canada',
		'CC': 'Cocos (Keeling) Islands',
		'CD': 'Congo, the Democratic Republic of the',
		'CF': 'Central African Republic',
		'CG': 'Congo',
		'CH': 'Switzerland',
		'CI': 'Côte d’Ivoire',
		'CK': 'Cook Islands',
		'CL': 'Chile',
		'CM': 'Cameroon',
		'CN': 'China',
		'CO': 'Colombia',
		'CR': 'Costa Rica',
		'CU': 'Cuba',
		'CV': 'Cape Verde',
		'CW': 'Curaçao',
		'CX': 'Christmas Island',
		'CY': 'Cyprus',
		'CZ': 'Czech Republic',
		'DE': 'Germany',
		'DJ': 'Djibouti',
		'DK': 'Denmark',
		'DM': 'Dominica',
		'DO': 'Dominican Republic',
		'DZ': 'Algeria',
		'EC': 'Ecuador',
		'EE': 'Estonia',
		'EG': 'Egypt',
		'EH': 'Western Sahara',
		'ER': 'Eritrea',
		'ES': 'Spain',
		'ET': 'Ethiopia',
		'FI': 'Finland',
		'FJ': 'Fiji',
		'FK': 'Falkland Islands (Malvinas)',
		'FM': 'Micronesia, Federated States of',
		'FO': 'Faroe Islands',
		'FR': 'France',
		'GA': 'Gabon',
		'GB': 'United Kingdom',
		'GD': 'Grenada',
		'GE': 'Georgia',
		'GF': 'French Guiana',
		'GG': 'Guernsey',
		'GH': 'Ghana',
		'GI': 'Gibraltar',
		'GL': 'Greenland',
		'GM': 'Gambia',
		'GN': 'Guinea',
		'GP': 'Guadeloupe',
		'GQ': 'Equatorial Guinea',
		'GR': 'Greece',
		'GS': 'South Georgia and the South Sandwich Islands',
		'GT': 'Guatemala',
		'GU': 'Guam',
		'GW': 'Guinea-Bissau',
		'GY': 'Guyana',
		'HK': 'Hong Kong',
		'HM': 'Heard Island and McDonald Islands',
		'HN': 'Honduras',
		'HR': 'Croatia',
		'HT': 'Haiti',
		'HU': 'Hungary',
		'ID': 'Indonesia',
		'IE': 'Ireland',
		'IL': 'Israel',
		'IM': 'Isle of Man',
		'IN': 'India',
		'IO': 'British Indian Ocean Territory',
		'IQ': 'Iraq',
		'IR': 'Iran, Islamic Republic of',
		'IS': 'Iceland',
		'IT': 'Italy',
		'JE': 'Jersey',
		'JM': 'Jamaica',
		'JO': 'Jordan',
		'JP': 'Japan',
		'KE': 'Kenya',
		'KG': 'Kyrgyzstan',
		'KH': 'Cambodia',
		'KI': 'Kiribati',
		'KM': 'Comoros',
		'KN': 'Saint Kitts and Nevis',
		'KP': 'Korea, Democratic People’s Republic of',
		'KR': 'Korea, Republic of',
		'KW': 'Kuwait',
		'KY': 'Cayman Islands',
		'KZ': 'Kazakhstan',
		'LA': 'Lao People’s Democratic Republic',
		'LB': 'Lebanon',
		'LC': 'Saint Lucia',
		'LI': 'Liechtenstein',
		'LK': 'Sri Lanka',
		'LR': 'Liberia',
		'LS': 'Lesotho',
		'LT': 'Lithuania',
		'LU': 'Luxembourg',
		'LV': 'Latvia',
		'LY': 'Libya',
		'MA': 'Morocco',
		'MC': 'Monaco',
		'MD': 'Moldova, Republic of',
		'ME': 'Montenegro',
		'MF': 'Saint Martin (French part)',
		'MG': 'Madagascar',
		'MH': 'Marshall Islands',
		'MK': 'Macedonia, the former Yugoslav Republic of',
		'ML': 'Mali',
		'MM': 'Myanmar',
		'MN': 'Mongolia',
		'MO': 'Macao',
		'MP': 'Northern Mariana Islands',
		'MQ': 'Martinique',
		'MR': 'Mauritania',
		'MS': 'Montserrat',
		'MT': 'Malta',
		'MU': 'Mauritius',
		'MV': 'Maldives',
		'MW': 'Malawi',
		'MX': 'Mexico',
		'MY': 'Malaysia',
		'MZ': 'Mozambique',
		'NA': 'Namibia',
		'NC': 'New Caledonia',
		'NE': 'Niger',
		'NF': 'Norfolk Island',
		'NG': 'Nigeria',
		'NI': 'Nicaragua',
		'NL': 'Netherlands',
		'NO': 'Norway',
		'NP': 'Nepal',
		'NR': 'Nauru',
		'NU': 'Niue',
		'NZ': 'New Zealand',
		'OM': 'Oman',
		'PA': 'Panama',
		'PE': 'Peru',
		'PF': 'French Polynesia',
		'PG': 'Papua New Guinea',
		'PH': 'Philippines',
		'PK': 'Pakistan',
		'PL': 'Poland',
		'PM': 'Saint Pierre and Miquelon',
		'PN': 'Pitcairn',
		'PR': 'Puerto Rico',
		'PS': 'Palestinian Territory, Occupied',
		'PT': 'Portugal',
		'PW': 'Palau',
		'PY': 'Paraguay',
		'QA': 'Qatar',
		'RE': 'Réunion',
		'RO': 'Romania',
		'RS': 'Serbia',
		'RU': 'Russian Federation',
		'RW': 'Rwanda',
		'SA': 'Saudi Arabia',
		'SB': 'Solomon Islands',
		'SC': 'Seychelles',
		'SD': 'Sudan',
		'SE': 'Sweden',
		'SG': 'Singapore',
		'SH': 'Saint Helena, Ascension and Tristan da Cunha',
		'SI': 'Slovenia',
		'SJ': 'Svalbard and Jan Mayen',
		'SK': 'Slovakia',
		'SL': 'Sierra Leone',
		'SM': 'San Marino',
		'SN': 'Senegal',
		'SO': 'Somalia',
		'SR': 'Suriname',
		'SS': 'South Sudan',
		'ST': 'São Tomé and Principe',
		'SV': 'El Salvador',
		'SX': 'Sint Maarten (Dutch part)',
		'SY': 'Syrian Arab Republic',
		'SZ': 'Swaziland',
		'TC': 'Turks and Caicos Islands',
		'TD': 'Chad',
		'TF': 'French Southern Territories',
		'TG': 'Togo',
		'TH': 'Thailand',
		'TJ': 'Tajikistan',
		'TK': 'Tokelau',
		'TL': 'Timor-Leste',
		'TM': 'Turkmenistan',
		'TN': 'Tunisia',
		'TO': 'Tonga',
		'TR': 'Turkey',
		'TT': 'Trinidad and Tobago',
		'TV': 'Tuvalu',
		'TW': 'Taiwan, Province of China',
		'TZ': 'Tanzania, United Republic of',
		'UA': 'Ukraine',
		'UG': 'Uganda',
		'UM': 'United States Minor Outlying Islands',
		'US': 'United States',
		'UY': 'Uruguay',
		'UZ': 'Uzbekistan',
		'VA': 'Holy See (Vatican City State)',
		'VC': 'Saint Vincent and the Grenadines',
		'VE': 'Venezuela, Bolivarian Republic of',
		'VG': 'Virgin Islands, British',
		'VI': 'Virgin Islands, U.S.',
		'VN': 'Viet Nam',
		'VU': 'Vanuatu',
		'WF': 'Wallis and Futuna',
		'WS': 'Samoa',
		'YE': 'Yemen',
		'YT': 'Mayotte',
		'ZA': 'South Africa',
		'ZM': 'Zambia',
		'ZW': 'Zimbabwe',
		// Non-Standard codes
		'EU': 'Europe',
		'II': 'International'
	}

};
